# Generated by Django 5.1.1 on 2024-10-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('listing', 'user', 'amount')},
        ),
    ]
